doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Apartment:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Apartment'
                prefix: 'App\Domain\Apartment'
                alias: Apartment
            ApartmentBookingHistory:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/ApartmentBookingHistory'
                prefix: 'App\Domain\ApartmentBookingHistory'
                alias: ApartmentBookingHistory
            HotelBookingHistory:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/HotelBookingHistory'
                prefix: 'App\Domain\HotelBookingHistory'
                alias: HotelBookingHistory
            Hotel:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Hotel'
                prefix: 'App\Domain\Hotel'
                alias: Hotel
            Booking:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Booking'
                prefix: 'App\Domain\Booking'
                alias: Booking
            ApartmentOffer:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/ApartmentOffer'
                prefix: 'App\Domain\ApartmentOffer'
                alias: ApartmentOffer
            HotelRoomOffer:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/HotelRoomOffer'
                prefix: 'App\Domain\HotelRoomOffer'
                alias: HotelRoomOffer
            Address:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Address'
                prefix: 'App\Domain\Address'
                alias: Address
            Space:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Space'
                prefix: 'App\Domain\Space'
                alias: Space
            Period:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Period'
                prefix: 'App\Domain\Period'
                alias: Period
            User:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/User'
                prefix: 'App\Domain\User'
                alias: User
            Money:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Money'
                prefix: 'App\Domain\Money'
                alias: Money
            RentalPlaceAvailability:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/RentalPlaceAvailability'
                prefix: 'App\Domain\RentalPlaceAvailability'
                alias: RentalPlaceAvailability