doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Apartment:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Apartment'
                prefix: 'App\Domain\Apartment'
                alias: Apartment
            ApartmentBookingHistory:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/ApartmentBookingHistory'
                prefix: 'App\Domain\ApartmentBookingHistory'
                alias: Apartment
            Hotel:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Hotel'
                prefix: 'App\Domain\Hotel'
                alias: Hotel
            HotelRoom:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/HotelRoom'
                prefix: 'App\Domain\HotelRoom'
                alias: HotelRoom
            Booking:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Booking'
                prefix: 'App\Domain\Booking'
                alias: Booking
            ApartmentOffer:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/ApartmentOffer'
                prefix: 'App\Domain\ApartmentOffer'
                alias: ApartmentOffer
            HotelRoomOffer:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/HotelRoomOffer'
                prefix: 'App\Domain\HotelRoomOffer'
                alias: HotelRoomOffer
