services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{Domain,Kernel.php}'

    App\Domain\EventChannel\EventChannel: '@App\Infrastructure\EventChannel\Symfony\SymfonyEventChannel'
    App\Domain\Booking\BookingRepository: '@App\Infrastructure\Persistence\Sql\Booking\SqlBookingRepository'
    App\Domain\ApartmentBookingHistory\ApartmentBookingHistoryRepository: '@App\Infrastructure\Persistence\Sql\ApartmentBookingHistory\SqlApartmentBookingHistoryRepository'
    App\Domain\HotelBookingHistory\HotelBookingHistoryRepository: '@App\Infrastructure\Persistence\Sql\HotelBookingHistory\SqlHotelBookingHistoryRepository'
    App\Domain\Apartment\ApartmentRepository: '@App\Infrastructure\Persistence\Sql\Apartment\SqlApartmentRepository'
    App\Domain\Hotel\HotelRepository: '@App\Infrastructure\Persistence\Sql\Hotel\SqlHotelRepository'
    App\Domain\ApartmentOffer\ApartmentOfferRepository: '@App\Infrastructure\Persistence\Sql\ApartmentOffer\SqlApartmentOfferRepository'
    App\Domain\HotelRoomOffer\HotelRoomOfferRepository: '@App\Infrastructure\Persistence\Sql\HotelRoomOffer\SqlHotelRoomOfferRepository'

    App\Framework\Symfony\Extension\RequestDTOResolver:
        arguments:
            - '@validator'
            - '@serializer'
        tags:
            - { name: controller.request_value_resolver, priority: 50 }

    app.event.event_id_factory:
        class: App\Domain\Event\EventIdFactory
    app.event.event_creation_time_factory:
        class: App\Domain\Event\EventCreationTimeFactory

    App\Domain\Apartment\ApartmentEventsPublisher:
        arguments:
            - '@app.event.event_id_factory'
            - '@app.event.event_creation_time_factory'
            - '@App\Domain\EventChannel\EventChannel'

    App\Domain\Hotel\HotelEventsPublisher:
        arguments:
            - '@app.event.event_id_factory'
            - '@app.event.event_creation_time_factory'
            - '@App\Domain\EventChannel\EventChannel'

    App\Domain\Booking\BookingEventsPublisher:
        arguments:
            - '@app.event.event_id_factory'
            - '@app.event.event_creation_time_factory'
            - '@App\Domain\EventChannel\EventChannel'