services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{Domain,Kernel.php}'

    App\Domain\Apartment\ApartmentRepository: '@App\Infrastructure\Persistence\Sql\Apartment\SqlApartmentRepository'

    App\Framework\Symfony\Extension\RequestDTOResolver:
        arguments:
            - '@validator'
            - '@serializer'
        tags:
            - { name: controller.request_value_resolver, priority: 50 }