services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{Domain,Kernel.php}'

    App\Domain\EventChannel\EventChannel: '@App\Infrastructure\EventChannel\Symfony\SymfonyEventChannel'
    App\Domain\Apartment\BookingRepository: '@App\Infrastructure\Persistence\Sql\Booking\SqlBookingRepository'
    App\Domain\ApartmentBookingHistory\ApartmentBookingHistoryRepository: '@App\Infrastructure\Persistence\Sql\ApartmentBookingHistory\SqlApartmentBookingHistoryRepository'
    App\Domain\HotelBookingHistory\HotelBookingHistoryRepository: '@App\Infrastructure\Persistence\Sql\HotelBookingHistory\SqlHotelBookingHistoryRepository'
    App\Domain\Apartment\ApartmentRepository: '@App\Infrastructure\Persistence\Sql\Apartment\SqlApartmentRepository'
    App\Domain\Hotel\HotelRepository: '@App\Infrastructure\Persistence\Sql\Hotel\SqlHotelRepository'
    App\Domain\HotelRoom\HotelRoomRepository: '@App\Infrastructure\Persistence\Sql\HotelRoom\SqlHotelRoomRepository'

    App\Framework\Symfony\Extension\RequestDTOResolver:
        arguments:
            - '@validator'
            - '@serializer'
        tags:
            - { name: controller.request_value_resolver, priority: 50 }